services:
  sudoku-api-1:
    build: .
    ports:
      - "8080:8080"
    environment:
      RUST_LOG: info

  sudoku-api-2:
    build: .
    ports:
      - "8081:8080"
    environment:
      RUST_LOG: info
    restart: always
